<p align="center">
<img src="https://numpy.org/images/logo.svg" width="80" height="">
</p>


https://numpy.org

 # **<font color="RoyalBlue">Conociendo NumPy</font>**

<p align="justify">
📘 NumPy, una abreviatura de "Numerical Python", tiene una historia que se remonta al comienzo del siglo XXI.
<br><br>
✅ <b>Inicios</b>
<br><br>
<b>Orígenes en el Lenguaje Python</b>: A principios de los años 2000, Travis Oliphant, un científico de datos y programador, estaba trabajando en proyectos que involucraban cálculos numéricos intensivos. Sin embargo, encontró que el rendimiento de Python en tales tareas era insuficiente debido a la falta de estructuras de datos eficientes para cálculos numéricos.
<br><br>
<b>Inspiración en MATLAB</b>: Travis se inspiró en la sintaxis y las capacidades de MATLAB, un lenguaje de programación ampliamente utilizado en matemáticas y ciencia de la computación. Buscaba crear un equivalente de código abierto y gratuito que pudiera ofrecer funcionalidades similares a las de MATLAB, pero integradas en Python.
<br><br>
✅ <b>Desarrollo de NumPy</b>
<br><br>
<b>Numerical Python (NumPy) 1.0</b>: En 2006, Travis Oliphant, junto con otros colaboradores, lanzó la versión 1.0 de NumPy. Esta biblioteca ofrecía estructuras de datos como arrays multidimensionales y funciones para operaciones matemáticas sobre los arrays.
<br><br>
<b>Código abierto y colaboración</b>: NumPy fue lanzado como un proyecto de código abierto bajo la licencia BSD, lo que permitió a la comunidad científica y de programación contribuir con mejoras y nuevas características.
<br><br>
✅ <b>Evolución y popularidad</b>
<br><br>
<b>Adopción en la comunidad científica</b>: NumPy rápidamente ganó popularidad entre los científicos de datos, ingenieros y académicos debido a su facilidad de uso y su eficiencia en el manejo de grandes volúmenes de datos numéricos.
<br><br>
<b>Ecosistema científico de Python</b>: La aparición de NumPy impulsó el crecimiento de un ecosistema completo de herramientas y bibliotecas científicas tales como SciPy, Matplotlib, Pandas y Scikit-learn, entre otras.

<p align="justify"> 👀 Por convención, de esta manera se importa <code>Numpy</code>:  </p>

In [ ]:
import numpy as np

 # **<font color="RoyalBlue">Introducción a NumPy</font>**

<p align="justify">
📘 NumPy es una biblioteca fundamental en el ecosistema de Python para la computación numérica y científica. Proporciona una manera eficiente de trabajar con arrays multidimensionales (también conocidos como matrices) y funciones matemáticas para realizar operaciones rápidas en estos arrays.
<br><br>
👀 Algunas de las características principales de NumPy incluyen:
<br><br>
<ul align = "justify">
<li>
<b>Eficiencia</b>: NumPy está implementado en C, lo que lo hace muy rápido y eficiente en comparación con las listas de Python estándar para operaciones numéricas.</li>
<li>
<b>Arrays Multidimensionales</b>: NumPy proporciona un objeto de array multidimensional llamado <code>ndarray</code>, que permite representar datos en forma de matrices de cualquier número de dimensiones.</li>
<li>
<b>Funciones Matemáticas</b>: NumPy incluye una amplia gama de funciones matemáticas para realizar operaciones numéricas en arrays, como sumas, productos, exponenciación, funciones trigonométricas, y otras funciones.</li>
<li>
<b>Indexación y Slicing Avanzados</b>: NumPy proporciona formas flexibles de acceder y manipular elementos individuales o subconjuntos de elementos en arrays utilizando técnicas de indexación y slicing.</li>
<li>
<b>Álgebra Lineal</b>: NumPy incluye un conjunto completo de funciones para realizar operaciones de álgebra lineal, como la multiplicación de matrices, la inversión de matrices y el cálculo de determinantes y valores propios.
</li></ul>


 # <font color="RoyalBlue"><b>Creación de arrays NumPy</font>

<p align="justify">
✅ Creación de Arrays NumPy
<br><br>
Una de las características más poderosas de NumPy es su capacidad para crear y manipular arrays de manera eficiente. Se puede crear arrays NumPy utilizando la función <code>numpy.array()</code> o utilizando otras funciones útiles, como <code>numpy.zeros()</code>, <code>numpy.ones()</code>, <code>numpy.arange()</code> y <code>numpy.linspace()</code>.


## <font color="RoyalBlue"><b>Array unidimensional


<p align="center">
<img src="https://github.com/cristiandarioortegayubro/BDS/blob/main/images/array1d.png?raw=true" width="150" height="">
</p>


### <font color="RoyalBlue"><b>Creando un array unidimensional


In [ ]:
arr1d = np.array([1, 2, 3, 4, 5])
arr1d

array([1, 2, 3, 4, 5])

In [ ]:
arr1d.shape

(5,)

<p align="justify">
👀 Este script crea un array unidimensional. Básicamente, este código representa la creación y visualización de un array unidimensional utilizando NumPy.

### <font color="RoyalBlue"><b>Creando un array de ceros


In [ ]:
zeros_arr1d = np.zeros((9))
zeros_arr1d

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

<p align="justify">
👀 Este script utiliza la función <code>np.zeros()</code> para crear un array unidimensional de longitud 9, lleno de ceros de manera eficiente.

### <font color="RoyalBlue"><b>Creando un array de unos


In [ ]:
ones_arr1d = np.ones((5))
ones_arr1d

array([1., 1., 1., 1., 1.])

<p align="justify">
👀 Este script utiliza la función <code>np.ones()</code> para crear un array unidimensional de longitud 5 de acuerdo al ejemplo, lleno de unos.

### <font color="RoyalBlue"><b>Creando un array con valores espaciados uniformemente


In [ ]:
range_arr = np.arange(0, 10, 2)
range_arr

array([0, 2, 4, 6, 8])

<p align = "justify">
👀 Este script utiliza la función <code>np.arange()</code> para crear un array unidimensional que contiene una secuencia de números comenzando desde 0 (inclusive), hasta 10 (exclusivo), con un paso de 2 entre cada número.
<br><br>
A continuación, otros ejemplos:

In [ ]:
range_arr = np.arange(0, 21, 5)
range_arr

array([ 0,  5, 10, 15, 20])

In [ ]:
range_arr = np.arange(0, 31, 3)
range_arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

### <font color="RoyalBlue"><b>Creando un array con valores espaciados linealmente


In [ ]:
linspace_arr = np.linspace(0, 5, 10)
linspace_arr

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

<p align="justify">
👀 Este script utiliza la función <code>np.linspace()</code> para crear un array unidimensional que contiene una secuencia de números uniformemente espaciados entre dos valores dados. En este caso, el array comienza en 0 y termina en 5, con un total de 10 elementos igualmente espaciados a lo largo de ese intervalo. Por lo tanto, contendrá valores distribuidos uniformemente entre 0 y 5, incluyendo ambos extremos.

👀 ahora con 5 elementos...

In [ ]:
linspace_arr = np.linspace(0, 5, 5)
linspace_arr

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

👀 si queremos valores enteros, entonces usamos el parámetro <code>dtype</code>

In [ ]:
linspace_arr = np.linspace(0, 5, 5, dtype=int)
linspace_arr

array([0, 1, 2, 3, 5])

## <font color="RoyalBlue"><b>Array bidimensional


<p align="center">
<img src="https://github.com/cristiandarioortegayubro/BDS/blob/main/images/array2d.png?raw=true" width="150" height="">
</p>


### <font color="RoyalBlue"><b>Creando un array bidimensional



In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

<p align="justify">
👀 Este script crea un array bidimensional con una lista de listas que contiene dos filas y tres columnas.
<br><br>
La primera fila contiene los elementos <code>[1, 2, 3]</code> y la segunda fila contiene los elementos <code>[4, 5, 6]</code>. En términos de matriz, esto representa una matriz con dos filas y tres columnas.

In [ ]:
arr2d.shape

(2, 3)

In [ ]:
arr_bidimensional = np.random.random((3, 3))
arr_bidimensional

array([[0.04265582, 0.29961952, 0.95269111],
       [0.09147089, 0.10829129, 0.7080117 ],
       [0.49817769, 0.64560793, 0.40623386]])

<p align="justify">
👀 Con la función <code>np.random.random()</code> se crea un array. Cada elemento de este array bidimensional es generado aleatoriamente y se encuentra en el rango de 0 a 1, siguiendo una distribución uniforme. Por lo tanto representa una matriz de 3 filas y 3 columnas, donde cada elemento es un número aleatorio entre 0 y 1.

### <font color="RoyalBlue"><b>Creando un array de ceros



In [ ]:
zeros_arr2d = np.zeros((3, 3))
zeros_arr2d

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
zeros_arr2d.shape

(3, 3)

### <font color="RoyalBlue"><b>Creando un array de unos



In [ ]:
ones_arr2d = np.ones((2, 2))
ones_arr2d

array([[1., 1.],
       [1., 1.]])

## <font color="RoyalBlue"><b>Array n-dimensional


<p align="center">
<img src="https://github.com/cristiandarioortegayubro/BDS/blob/main/images/array3d.png?raw=true" width="180" height="">
</p>


In [ ]:
arr_3d = np.random.random((2, 3, 4))
arr_3d

array([[[0.82487753, 0.46307364, 0.84178052, 0.12877921],
        [0.98773425, 0.33846272, 0.50773035, 0.13441338],
        [0.8905191 , 0.32200432, 0.27308353, 0.37908094]],

       [[0.26564289, 0.45536572, 0.85611282, 0.15469387],
        [0.14978446, 0.07002455, 0.98424159, 0.21486234],
        [0.262579  , 0.28292073, 0.06295597, 0.91892918]]])

 # **<font color="RoyalBlue">Indexación y Slicing</font>**

<p align="justify">
✅ NumPy permite acceder a elementos individuales, filas, columnas y secciones de arrays utilizando indexación y slicing. Esto proporciona una forma eficiente de manipular y trabajar con datos en arrays NumPy.



 ## **<font color="RoyalBlue">Indexación de arrays unidimensionales</font>**

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5])

In [ ]:
len(arr)

6

In [ ]:
primer_elemento = arr[0]
primer_elemento

0

In [ ]:
ultimo_elemento = arr[-1]
ultimo_elemento

5

In [ ]:
sub_array = arr[2:5]
sub_array

array([2, 3, 4])

 ## **<font color="RoyalBlue">Indexación de arrays bidimensionales</font>**

In [ ]:
arr_2d = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr_2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
elemento = arr_2d[1, 1]
elemento

4

In [ ]:
fila = arr_2d[1]
fila

array([3, 4, 5])

In [ ]:
columna = arr_2d[:, 1]
columna

array([1, 4, 7])

In [ ]:
seccion = arr_2d[:2, 1:]
seccion

array([[1, 2],
       [4, 5]])

 ## **<font color="RoyalBlue">Indexación con expresiones booleanas</font>**

In [ ]:
rand_arr = np.random.random(5)
rand_arr

array([0.05062282, 0.90786647, 0.0261457 , 0.40059993, 0.4581833 ])

In [ ]:
mascara = rand_arr > 0.5
mascara

array([False,  True, False, False, False])

In [ ]:
valores_seleccionados = rand_arr[mascara]
valores_seleccionados

array([0.90786647])

 # **<font color="RoyalBlue">Operaciones básicas de álgebra lineal</font>**

<p align="justify">
✅ NumPy proporciona un conjunto completo de funciones para realizar operaciones básicas de álgebra lineal en arrays NumPy. Estas operaciones son fundamentales en el análisis de datos y el aprendizaje automático.
<br><br>
A continuación, se presentan algunos ejemplos de operaciones básicas de álgebra lineal:



 ## **<font color="RoyalBlue">Transposición de matrices</font>**

In [ ]:
matriz = np.array([[1, 2], [3, 4]])
matriz

array([[1, 2],
       [3, 4]])

In [ ]:
transpuesta = np.transpose(matriz)
transpuesta

array([[1, 3],
       [2, 4]])

 ## **<font color="RoyalBlue">Multiplicación de matrices</font>**

In [ ]:
matriz1 = np.array([[1, 2], [3, 4]])
matriz1

array([[1, 2],
       [3, 4]])

In [ ]:
matriz2 = np.array([[5, 6], [7, 8]])
matriz2

array([[5, 6],
       [7, 8]])

In [ ]:
producto = np.dot(matriz1, matriz2)
producto

array([[19, 22],
       [43, 50]])

 ## **<font color="RoyalBlue">Cálculo de determinantes</font>**

In [ ]:
matriz

array([[1, 2],
       [3, 4]])

In [ ]:
determinante = np.linalg.det(matriz)
determinante.round(4)

-2.0

 ## **<font color="RoyalBlue">Cálculo de inversas</font>**

In [ ]:
matriz

array([[1, 2],
       [3, 4]])

In [ ]:
inversa = np.linalg.inv(matriz)
inversa

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

 ## **<font color="RoyalBlue">Resolución de sistemas de ecuaciones lineales</font>**

In [ ]:
A = np.array([[2, 3], [4, 5]])
A

array([[2, 3],
       [4, 5]])

In [ ]:
b = np.array([1, 2])
b

array([1, 2])

In [ ]:
x = np.linalg.solve(A, b)
x

array([0.5, 0. ])

<p align="justify">
👀 Este script utiliza la función <code>np.linalg.solve()</code> para resolver un sistema de ecuaciones lineales representado por la matriz $A$ y el vector $b$.
<br><br>
La función <code>np.linalg.solve()</code> encuentra la solución para el vector <code>x</code> que satisface la ecuación $Ax = b$, donde $A$ es una matriz y $b$ es un vector, y se asigna el resultado a la variable $x$.

 # **<font color="RoyalBlue">Operaciones básicas de estadística descriptiva</font>**

In [ ]:
arr_aleatorio = np.random.randint(0, 505, 30)
arr_aleatorio

array([397,   2, 499, 205, 441, 202, 469, 179, 459, 206, 160, 454, 274,
       476, 259,  73, 334, 370, 347, 271,   7, 119, 166,  63, 272, 239,
        86,  54, 120, 285])

👀 Este script genera un rango de 30 valores enteros, entre 0 y 505.

 ## **<font color="RoyalBlue">Máximos y mínimos</font>**

In [ ]:
valor_maximo = np.max(arr_aleatorio)
valor_maximo

499

In [ ]:
valor_minimo = np.min(arr_aleatorio)
valor_minimo

2

 ## **<font color="RoyalBlue">Media, mediana y desviación estándar</font>**

In [ ]:
media = np.mean(arr_aleatorio).round(2)
media

249.6

In [ ]:
mediana = np.median(arr_aleatorio)
mediana

249.0

In [ ]:
desviacion_estandar = np.std(arr_aleatorio)
desviacion_estandar.round(2)

147.3

 ## **<font color="RoyalBlue">Normalizado</font>**

In [ ]:
arr_aleatorio

array([397,   2, 499, 205, 441, 202, 469, 179, 459, 206, 160, 454, 274,
       476, 259,  73, 334, 370, 347, 271,   7, 119, 166,  63, 272, 239,
        86,  54, 120, 285])

In [ ]:
arr_normalizado = (arr_aleatorio - np.min(arr_aleatorio)) / (np.max(arr_aleatorio) - np.min(arr_aleatorio))
arr_normalizado

array([0.38157895, 0.45833333, 0.1754386 , 0.61184211, 0.75877193,
       0.60087719, 0.43201754, 0.61403509, 0.03070175, 0.55701754,
       0.66447368, 0.92324561, 0.36403509, 0.62938596, 0.02412281,
       1.        , 0.19078947, 0.39692982, 0.14254386, 0.86184211,
       0.95394737, 0.        , 0.50438596, 0.81798246, 0.71052632,
       0.82675439, 0.46710526, 0.38157895, 0.77412281, 0.47807018])

 # **<font color="RoyalBlue">Ejercicios prácticos</font>**

<p align="justify">
✅ A continuación, se presentan algunos ejercicios prácticos para aplicar los conceptos de este colab:
<br><br>

🏷 **a. Ejercicio 1: Creación de Arrays:**
   - Crea un array unidimensional con los números del 1 al 10.
   - Crea un array bidimensional de tamaño 3x3 con valores aleatorios entre 0 y 1.
   - Crea un array tridimensional de tamaño 2x2x2 con unos.

🏷 **b. Ejercicio 2: Indexación y Slicing:**
   - Accede al tercer elemento del array unidimensional creado en el ejercicio 1.
   - Accede a la primera fila del array bidimensional creado en el ejercicio 1.
   - Accede a la primera columna del array bidimensional creado en el ejercicio 1.
   - Accede a la última fila y última columna del array bidimensional creado en el ejercicio 1.

🏷 **c. Ejercicio 3: Operaciones Básicas de Álgebra Lineal:**
   - Crea dos matrices 2x2 y realiza la multiplicación de matrices.
   - Calcula el determinante de una matriz 3x3.
   - Calcula la inversa de una matriz 2x2.
   - Resuelve el siguiente sistema de ecuaciones lineales:
     - 2x + 3y = 1
     - 4x + 5y = 2

🏷 **d. Ejercicio 4: Aplicación de Funciones NumPy:**
   - Crea un array unidimensional de tamaño 10 con valores aleatorios entre 0 y 100.
   - Calcula la media, la mediana y la desviación estándar del array creado.
   - Encuentra el valor máximo y mínimo del array creado.
   - Normaliza el array para que todos sus valores estén en el rango de 0 a 1.

🏷 **e. Ejercicio 5: Manipulación de Datos:**
   - Crea un array bidimensional de tamaño 3x3 con valores aleatorios enteros entre 1 y 10.
   - Filtra los valores mayores que 5 en el array creado.
   - Reemplaza todos los valores mayores que 5 en el array creado por el valor 10.

<p align="justify">
<br>
✅ A continuación, las soluciones sugeridas:
<br><br>

🏷 **a. Ejercicio 1: Creación de Arrays:**
```python
# Crear un array unidimensional con los números del 1 al 10
arr_unidimensional = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Crear un array bidimensional de tamaño 3x3 con valores aleatorios entre 0 y 1
arr_bidimensional = np.random.random((3, 3))

# Crear un array tridimensional de tamaño 2x2x2 con unos
arr_tridimensional = np.ones((2, 2, 2))
```

🏷 **b. Ejercicio 2: Indexación y Slicing:**
```python
# Acceder al tercer elemento del array unidimensional creado en el ejercicio 1
tercer_elemento = arr_unidimensional[2]

# Acceder a la primera fila del array bidimensional creado en el ejercicio 1
primera_fila = arr_bidimensional[0]

# Acceder a la primera columna del array bidimensional creado en el ejercicio 1
primera_columna = arr_bidimensional[:, 0]

# Acceder a la última fila y última columna del array bidimensional creado en el ejercicio 1
ultima_fila = arr_bidimensional[-1]
ultima_columna = arr_bidimensional[:, -1]
```

🏷 **c. Ejercicio 3: Operaciones Básicas de Álgebra Lineal:**
```python
# Crear dos matrices 2x2
matriz1 = np.array([[1, 2], [3, 4]])
matriz2 = np.array([[5, 6], [7, 8]])

# Realizar la multiplicación de matrices
producto = np.dot(matriz1, matriz2)

# Calcular el determinante de una matriz 3x3
matriz3x3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
determinante = np.linalg.det(matriz3x3)

# Calcular la inversa de una matriz 2x2
inversa = np.linalg.inv(matriz1)

# Resolver el sistema de ecuaciones lineales
A = np.array([[2, 3], [4, 5]])
b = np.array([1, 2])
x = np.linalg.solve(A, b)
```

🏷 **d. Ejercicio 4: Aplicación de Funciones NumPy:**
```python
# Crea un array unidimensional de tamaño 10 con valores aleatorios entre 0 y 100
arr_aleatorio = np.random.randint(0, 101, 10)

# Calcula la media, la mediana y la desviación estándar del array creado
media = np.mean(arr_aleatorio)
mediana = np.median(arr_aleatorio)
desviacion_estandar = np.std(arr_aleatorio)

# Encuentra el valor máximo y mínimo del array creado
valor_maximo = np.max(arr_aleatorio)
valor_minimo = np.min(arr_aleatorio)

# Normaliza el array para que todos sus valores estén en el rango de 0 a 1
arr_normalizado = (arr_aleatorio - np.min(arr_aleatorio)) / (np.max(arr_aleatorio) - np.min(arr_aleatorio))
```

🏷 **e. Ejercicio 5: Manipulación de Datos:**
```python
# Crea un array bidimensional de tamaño 3x3 con valores aleatorios enteros entre 1 y 10
arr_enteros = np.random.randint(1, 11, (3, 3))

# Filtra los valores mayores que 5 en el array creado
valores_mayores_5 = arr_enteros[arr_enteros > 5]

# Reemplaza todos los valores mayores que 5 en el array creado por el valor 10
arr_enteros[arr_enteros > 5] = 10
```

<br>
<br>
<p align="center"><b>
💗
<font color="RoyalBlue">
Hemos llegado al final de nuestro colab, a seguir codeando en NumPy...
</font>
</p>
